### ISSUE TITLE
Миксины

### ISSUE THREAD

**Issue by Fr0stmourne** [rsilivestr/FSD2ndTask#10]
Нужно всё содержимое блока прокидывать через объект в миксин вместо хардкода прям в теле миксина
Например, в файле футера должен быть 1 миксин, в который прокидывается все наполнение (ссылки, описание, заголовки, ...). В этом случае не придется делать миксин footerRU и там всё дублировать с другим текстом ссылок. В итоге должно получиться так, что наполнение должно быть указано на странице, где используются миксины, и передаваться в них как параметр
Вспомогательные миксины лучше вынести (например, в папке footer создать папку components и туда всё это сложить)
![image](https://user-images.githubusercontent.com/46089168/99267602-33100e00-2835-11eb-849c-b575876295a1.png)

**Comment by rsilivestr** [comment]
Создал ветку footer (359c496, 782cfdd).

Теперь на каждой странице приходится в миксин передавать портянку на 70 строк.
Хардкод гораздо удобней при подключении на страницах. Плюс в макете уже нет английского футера - на всех одинаковый.

@Fr0stmourne, на твое усмотрение сливаю с мастером или переделываю.

**Comment by rsilivestr** [comment]
Изменил миксины footer (89b4323), header (347cffc). Принимают наполнение как объект, имеют наполнение по умолчанию.

**Comment by rsilivestr** [comment]
Изменил миксины блоков
- image-title ab0ec1e2fdce5c02e876cabe33718c5555f64d64
- user-comment ab0ec1e2fdce5c02e876cabe33718c5555f64d64
- date-dropdown 21af35e1b4c177c9d73fa60fb8d0bb683a44cd7f
- pagination 0399f510740fd1594550736ac1e0b5640fba1c0d
