### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by Fr0stmourne** [rsilivestr/FSD2ndTask#11]
Есть места (например, вот это), где вдруг появляется вообще не связанный блок (full-width-container в данном случае). Все элементы должны к 1 блоку относиться. Можешь воспользоваться sass-миксинами, чтобы вынести этот стиль контейнера, если он много где используется. Еще такой момент, что название папки, файла, миксина и корневого блока должны совпадать, а тут footer/main-footer, лучше привести к чему-то одному
![image](https://user-images.githubusercontent.com/46089168/99268981-e0375600-2836-11eb-8aca-6da79e725f01.png)

**Comment by Fr0stmourne** [comment]
Какой-то не совсем стандартный БЭМ, тут ключ модификатора отделен 2 дефисами, а его значение подчеркиванием?
![image](https://user-images.githubusercontent.com/46089168/101032650-ffe6b200-358a-11eb-8f63-a7e629a10d5e.png)

**Comment by rsilivestr** [comment]
> Какой-то не совсем стандартный БЭМ, тут ключ модификатора отделен 2 дефисами, а его значение подчеркиванием?

Именно. На Риззоме не нашел четких требований по схеме именования, а в методологии сказано, что
>Можно создать собственную схему именования БЭМ-сущностей. Важно, чтобы разделители в новой схеме давали возможность на программном уровне отделять блоки от элементов и модификаторов.

Не помню, увидел ли я где эту схему или сам придумал, но мне нравится больше стандартной.
