### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by Fr0stmourne** [rsilivestr/FSD2ndTask#13]
Лучше разнести стили, которые перетирают стили плагина, и свои стили по разным файлам
![image](https://user-images.githubusercontent.com/46089168/101039973-0b3add00-358d-11eb-8568-703db7a2ab2d.png)

**Comment by Fr0stmourne** [comment]
В css тоже нужно поправить разбиение по принципу 1 файл - 1 блок, в form.sass например блоки .bill-info и .form

**Comment by Fr0stmourne** [comment]
Надо по максимуму избавиться от фиксированных высот/ширин, например, в хедере я не вижу необходимости в фиксированной высоте
![image](https://user-images.githubusercontent.com/46089168/101042241-04609a00-358e-11eb-8bf3-03c772221c7f.png)

**Comment by Fr0stmourne** [comment]
Перенос строк во флексах тоже для динамических блоков запрещать не стоит, если там добавится контент, то пусть оно перенесется и будет не очень красиво, чем вообще не отобразится или будут артефакты какие-то

**Comment by rsilivestr** [comment]
>Лучше разнести стили, которые перетирают стили плагина, и свои стили по разным файлам

>Перенос строк во флексах тоже для динамических блоков запрещать не стоит

Изменил в 9cf0b69.

>В css тоже нужно поправить разбиение по принципу 1 файл - 1 блок

Добавил блоки bill-info, room-title, разнес инпуты по отдельным блокам.

>Надо по максимуму избавиться от фиксированных высот/ширин

Убрал, кроме блоков с фиксированным размером (ссылки пагинации, диаграмма рейтинга).

**Comment by Fr0stmourne** [comment]
А зачем нужны эти классы? это типа атомарный css на минималках?)
![image](https://user-images.githubusercontent.com/46089168/101525334-357d0800-399c-11eb-985b-856b7ac2bb90.png)

**Comment by Fr0stmourne** [comment]
Разве для этих иконок нужна максимальная ширина? Получается, что больше ни 1 иконки не добавить, потому что не влезет, и не убрать, потому что 2 оставшиеся разнесет сильно. Думаю, лучше просто между ними отступ сделать
![image](https://user-images.githubusercontent.com/46089168/101527947-b5f13800-399f-11eb-8bd0-016d8e497016.png)

**Comment by rsilivestr** [comment]
>Разве для этих иконок нужна максимальная ширина?

Убрал width, добавил gap.

>А зачем нужны эти классы? это типа атомарный css на минималках?)
![image](https://user-images.githubusercontent.com/31914503/101750444-0bccf980-3ae0-11eb-9941-408958e81432.png)

Миксы для uikit. 
Еще есть миксы margin-bottom (`src/styles/mb.sass`). Perfect pixel без этих миксов не сделать, т.к. в макете везде разные расстояния между блоками и элементами в блоках.
