### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by AkhmadBabaev** [rsilivestr/FSD2ndTask#18]
https://github.com/rsilivestr/FSD2ndTask/blob/0422993f7b041490b925aef8bff95f1775afdd12/.gitignore#L2

В файле .gitignore проекта лучше принято игнорировать файлы свойственные для конкретного проекта, а остальные файлы которые привязаны к конкретному пользователю как например файлы твоего редактора кода или твоей ОС лучше игнорировать на остальных уровнях гит конфигурации, на уровне пользователя или на уровне системы.

**Comment by rsilivestr** [comment]
27958b52fac155d1f63eb6953a16bd67c62b1936
