### ISSUE TITLE
Pug

### ISSUE THREAD

**Issue by AkhmadBabaev** [rsilivestr/FSD2ndTask#19]
Заметил инструкцию var в pug файлах, старайся придерживаться хороших практика eslint airbnb везде ) Так же добавлю что код который ты вынес в объекты как например в папке компонента dropdown, можно вынести в отдельный файл и импортировать объекты тем самым сделав свои компоненты чище. Я бы посоветовал по чаще использовать этот прием.

**Comment by AkhmadBabaev** [comment]
https://github.com/rsilivestr/FSD2ndTask/blob/0422993f7b041490b925aef8bff95f1775afdd12/src/components/common.blocks/dropdown/dropdown.pug#L75-L77

Такие конструкции атрибутах с тернарным оператором в большинстве случаев бывает возможно заменить на условия &&, получится: 

```pug
.dropdown(class = forceOpen && 'dropdown--force-open')&attributes(attributes) 
```

**Comment by rsilivestr** [comment]
> Заметил инструкцию var в pug файлах

aa3043f01807b36c05e1fabcf6a92ed32b00b48a

Импортировать константы из отдельных файлов:

7ec73dbc4c097d18a258d257edf3299e6df66862, 7982294a5ec9d0f85b462c1f7ec97bd2584580b9

**Comment by AkhmadBabaev** [comment]
https://github.com/rsilivestr/FSD2ndTask/blob/25ffcf866380391f27c8f368b808ca7bc902101b/src/components/common.blocks/bill-info/bill-info.pug#L6-L18

Тут явно можно использовать цикл ) Пересмотри проект может ещё где найдёшь такие места.
Думаю данные контент элементов title и sum так же можно вынести в отдельный файл.

Я увидел что ты вынес большие объекты из js файлов но это ещё касалось и pug файлов, объекты **DROPDOWN_DEFAULT_CONFIG** и **DROPDOWN_MULTI_DEFAULT_CONFIG** можно вынести из dropdown.pug в json файл например и импортировать его в pug файл с помощью require. Обрати внимание что в таком случае нужно как-то определять какой файл с данными принадлежит pug файлам, а какой js, можно добавить какой-нибудь префикс по типу **data.pug.json** или **fixtures.pug.json**.

**Comment by rsilivestr** [comment]
| вынести из dropdown.pug в json файл

Так вот как это делается. А я безуспешно пробовал в .js и .pug выносить.

**Comment by AkhmadBabaev** [comment]
https://github.com/rsilivestr/FSD2ndTask/blob/fb064e6222d8ed8e71574b18391fd494bc9d24ac/src/components/button/button.pug#L1-L12

Сложно написан компонент, возникает много вопрос, нужно пересмотреть ) mixin aButton имеет параметр disabled, но в атрибут устанавливается isDisabled, не понятно зачем там тернарный оператор. 

Почему совсем не используешь переменные с деструктуризации, так как по airbnb от которого мы сильно отталкиваемся желательно использовать диструктуризацию там где это уместно.

Предпочтительнее использовать очевидные названия, к примеру вместо aButton, ButtonLink.

**Comment by AkhmadBabaev** [comment]
https://github.com/rsilivestr/FSD2ndTask/blob/aeb97e3d065b69324d40aa52e2fe36380d19f54d/src/components/form/--type/login/login.pug#L9-L11

Судя по заголовку без класса ты полагаешься на глобальные стили для тэгов заголовков, тут должен быть класс .form__title у которого будут необходимые стили.

**Comment by AkhmadBabaev** [comment]
https://github.com/rsilivestr/FSD2ndTask/blob/aeb97e3d065b69324d40aa52e2fe36380d19f54d/src/pages/form-elements/form-elements.pug#L20-L22

Сейчас миксин head это больше тэг head, почему-то он может включать в себя body. В pug  можно создавать layouts более удобным способом чем миксины, почитай [тут](https://pugjs.org/language/inheritance.html) и имя head соответственно стоит поменять.

**Comment by AkhmadBabaev** [comment]
https://github.com/rsilivestr/FSD2ndTask/blob/aeb97e3d065b69324d40aa52e2fe36380d19f54d/src/components/logo/logo.pug#L1-L4 

Старайся не создавать несколько миксинов в одном файле, это крайние случаи. Обычное миксин лого предпочтительнее назвать просто logo, а для лого которое существует только в рамках ui макета, можно добавить префикс UI, получаем UILogo .

Для компонентов существующих только в пределах ui, можно создать отдельную папку внутри папки components или на уровне с папкой components и в этой папке создать папку logo с миксином UILogo. Тоже самое касается компонента сolorBox и может есть ещё. Объединение элементов живущих только в ui с обычными, дает дополнительную умственную нагрузку на читателя, а так же создает ситуацию, при которой можно писать стили и логику 2 типов компонентов в общих sass или js файлах, а клиенту который никогда не увидит ui макет не нужно грузить стили которые встречаются только в нём.

**Comment by AkhmadBabaev** [comment]
https://github.com/rsilivestr/FSD2ndTask/blob/60ed9f8502dfd661fc2b0fc0faf5deedc28eb07d/src/components/date-dropdown/FSD2ndTaskDatepicker.js#L12-L31

Если сократить время жизни переменных, читабельность выделенного участка кода увеличится. [Readme](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#1.7).
Для примера сократил время жизни переменной **buttons**
```js
    const buttons = document.createElement('div');
    buttons.className = 'datepicker__buttons-panel';
    buttons.appendChild(clearBtn);
    buttons.appendChild(applyBtn);
    return buttons;
```

**Comment by AkhmadBabaev** [comment]
https://github.com/rsilivestr/FSD2ndTask/blob/60ed9f8502dfd661fc2b0fc0faf5deedc28eb07d/src/components/dropdown/FSD2ndTaskDropdown.js#L12-L20

По стандартам если в if проверяется несколько условий то желательно поступать [так](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#1.9). Это не всегда получается, так что можно делать и исключения.
