### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by AkhmadBabaev** [rsilivestr/FSD2ndTask#21]
https://github.com/rsilivestr/FSD2ndTask/blob/aeb97e3d065b69324d40aa52e2fe36380d19f54d/src/components/header/header.js#L1-L12

Файл header.js содержит много функций связанных с хедером, выглядит как не созданный компонент. Пересмотри пожалуйста нету ли возможности создать из него нормальный компонент.

**Comment by rsilivestr** [comment]
>Файл header.js содержит много функций связанных с хедером, выглядит как не созданный компонент. Пересмотри пожалуйста нету ли возможности создать из него нормальный компонент.

c40516b3411202ceb9d06243f8bf17424ab7875d

**Comment by AkhmadBabaev** [comment]
https://github.com/rsilivestr/FSD2ndTask/blob/60ed9f8502dfd661fc2b0fc0faf5deedc28eb07d/src/components/dropdown/FSD2ndTaskDropdown.js#L12-L20

По стандартам если в if проверяется несколько условий то желательно поступать [так](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#1.9). Это не всегда получается, так что можно делать и исключения.

**Comment by AkhmadBabaev** [comment]
https://github.com/rsilivestr/FSD2ndTask/blob/60ed9f8502dfd661fc2b0fc0faf5deedc28eb07d/src/components/date-dropdown/FSD2ndTaskDatepicker.js#L12-L31

Если сократить время жизни переменных, читабельность выделенного участка кода увеличится. [Readme](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#1.7). Пересмотри код, думаю найдутся ещё переменные время жизни которых можно сократить.
Для примера сократил время жизни переменной **buttons**
```js
    const buttons = document.createElement('div');
    buttons.className = 'datepicker__buttons-panel';
    buttons.appendChild(clearBtn);
    buttons.appendChild(applyBtn);
    return buttons;
```

**Comment by AkhmadBabaev** [comment]
https://github.com/rsilivestr/FSD2ndTask/blob/60ed9f8502dfd661fc2b0fc0faf5deedc28eb07d/src/components/masked-date/FSD2ndTaskMaskedDate.js#L1-L2

По стандартам импорты сортируем [так](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#1.17).

**Comment by AkhmadBabaev** [comment]
https://github.com/rsilivestr/FSD2ndTask/blob/60ed9f8502dfd661fc2b0fc0faf5deedc28eb07d/src/components/star-rating/FSD2ndTaskRating.js#L6-L12

Когда весь метод является одним блоком if, можно переписать его так 
```js
  _setRating(target) {
    if (!target.classList.contains('star-rating__star')) return;

    this.activeStar.classList.remove('star-rating__star--active');
    this.activeStar = target;
    this.activeStar.classList.add('star-rating__star--active');
  }
```

Такой способ уменьшит уровень вложенности, тем самым улучшится читаемость, особенно полезно когда уровень вложенности больше текущего.

**Comment by AkhmadBabaev** [comment]
https://github.com/rsilivestr/FSD2ndTask/blob/72aa1b1a3d8bbc8e8f4f690dd42abddeebcb8ec2/src/components/dropdown/Dropdown.js#L184-L193

Предпочтительнее будет избавиться от стрелочной функции в addEventListener над обработчиками, а для привязки методов к классу можно использовать пакет [autobind-decorator](https://www.npmjs.com/package/autobind-decorator) или аналоги, благодаря этому будет очевиднее какой метод привязан, чем bind в конструкторе класса или где-либо ещё.

**Comment by AkhmadBabaev** [comment]
https://github.com/rsilivestr/FSD2ndTask/blob/72aa1b1a3d8bbc8e8f4f690dd42abddeebcb8ec2/src/components/like-counter/LikeCounter.js#L17-L20

Элементы input и value должны иметь префикс js-, то есть в pug у тебя будет 
```pug
span.like-counter__value.js-like-counter__value= value
```
