### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by AkhmadBabaev** [rsilivestr/FSD2ndTask#24]
![изображение](https://user-images.githubusercontent.com/51095975/111006446-daddb880-839d-11eb-9813-a0fdd63533d5.png)

В данное поле можно ввести только тот текст что соответствует маске **ДД.ММ.ГГГГ**, в данном случае проходить будут только цифры, а точки после значений ДД и ММ должны проставляться автоматически. Дополнительно стоит позаботиться о валидности даты, то есть не может быть 15-ый месяц или цифра 2 в качестве первого значения месяца, ты можешь просто не пропускать некорректные значение либо оповещать об этом сообщением по типу - **Некорректная дата**. Пример

![изображение](https://user-images.githubusercontent.com/51095975/110520650-d1dfb380-811f-11eb-818b-4c98c248de0c.png)

**Comment by AkhmadBabaev** [comment]
![изображение](https://user-images.githubusercontent.com/51095975/111006660-432c9a00-839e-11eb-9e04-ffec483f0e4a.png)

Клик на поля ничего не делает ) может что-то отвалилось.

**Comment by AkhmadBabaev** [comment]
![изображение](https://user-images.githubusercontent.com/51095975/111006756-6ce5c100-839e-11eb-9782-71b7e0604ab7.png)

Пустые поля, а так же по клику на кнопки добавить/удалить ничего не происходит.

**Comment by AkhmadBabaev** [comment]
![изображение](https://user-images.githubusercontent.com/51095975/111006927-b9310100-839e-11eb-97ac-a997bec0ad71.png)

По клику по пустому пространству происходит переключение чекбокса, не должно по идее.

**Comment by AkhmadBabaev** [comment]
![изображение](https://user-images.githubusercontent.com/51095975/111007053-01e8ba00-839f-11eb-83f6-7c0bbd8f08c4.png)

Тэг button по дефолту имеет type submit, так не хорошо, так как когда такая кнопка оказывается внутри формы, клик по ней может вызывать отправку формы, нужно явно указывать type button, для тех кнопок что не должны вызывать отправку формы.

**Comment by AkhmadBabaev** [comment]
![изображение](https://user-images.githubusercontent.com/51095975/111220708-94c96480-85ea-11eb-889e-de4a97d4f2f3.png)

* Когда календарь открыт, клик за пределами календаря должен его закрывать ) 
* Шрифты в календаре отличаются от тех что в макете. 
* Нужно запретить возможность бронировать номера задних чисел(дней которые уже прошли).

**Comment by AkhmadBabaev** [comment]
![изображение](https://user-images.githubusercontent.com/51095975/111221608-c4c53780-85eb-11eb-94bd-e90a6df8c04a.png)

Что-то пошло не так.

**Comment by AkhmadBabaev** [comment]
![изображение](https://user-images.githubusercontent.com/51095975/111222221-96942780-85ec-11eb-8d08-d9da8dc5d12b.png)

Тут тоже что-то пошло не так )

**Comment by AkhmadBabaev** [comment]
Кнопка лайк отличается от той что в макете.

**Comment by AkhmadBabaev** [comment]
![изображение](https://user-images.githubusercontent.com/51095975/111223303-07880f00-85ee-11eb-8cf8-cbfbd3a285b7.png)

Для такого рода списков можно подумать об использовании семантических тэгов.

**Comment by AkhmadBabaev** [comment]
![изображение](https://user-images.githubusercontent.com/51095975/111223442-34d4bd00-85ee-11eb-9d88-cee4a324ba4c.png)

Клик по пустой области переключает кнопку.

**Comment by AkhmadBabaev** [comment]
![изображение](https://user-images.githubusercontent.com/51095975/111223819-b4628c00-85ee-11eb-9f97-a2348c93b8c3.png)

Лучше явно добавить данный футер на страницу так как в макете он присутствует.

**Comment by AkhmadBabaev** [comment]
![изображение](https://user-images.githubusercontent.com/51095975/111224054-00153580-85ef-11eb-850e-35bbfce8b74f.png)

Касаемо того куда должны вести ссылки для которых нет страниц можно почитать [тут](https://github.com/fullstack-development/front-end-best-practices/tree/master/HTML#%D1%82%D0%B5%D0%B3%D0%B8).

**Comment by AkhmadBabaev** [comment]
![изображение](https://user-images.githubusercontent.com/51095975/111224721-e6282280-85ef-11eb-81f9-5de480d3386e.png)

Счётчик можно было сделать простым div/span. В текущем варианте я могу вводить туда не числовые значения, либо числа которые выше установленного придела, допустим число 100, у получу 100 гостей в итоге.

**Comment by rsilivestr** [comment]
<details>

![изображение](https://user-images.githubusercontent.com/51095975/111222221-96942780-85ec-11eb-8d08-d9da8dc5d12b.png)

</details>

> Тут тоже что-то пошло не так )

Нет, все правильно. Это uikit, там позиционирование абсолютное между блоками элементов.

**Comment by rsilivestr** [comment]
>Кнопка лайк отличается от той что в макете.

<details><summary>wut?!</summary>

![image](https://user-images.githubusercontent.com/31914503/111270400-dbe24480-8640-11eb-975e-e6e680ddb055.png)


</details>

**Comment by AkhmadBabaev** [comment]
> wut?!

![изображение](https://user-images.githubusercontent.com/51095975/111275468-38486280-8647-11eb-9e8a-2d70df991e4a.png)
![изображение](https://user-images.githubusercontent.com/51095975/111275701-7e9dc180-8647-11eb-91c9-085674e87c82.png)

В макете рамка имеет градиент, а сердце нет, у тебя наоборот )

**Comment by AkhmadBabaev** [comment]
![изображение](https://user-images.githubusercontent.com/51095975/111276028-f0760b00-8647-11eb-8c81-eaad6592f5f8.png)

**Comment by AkhmadBabaev** [comment]
![изображение](https://user-images.githubusercontent.com/51095975/111276304-42b72c00-8648-11eb-8300-27af4cd73da1.png)

**Comment by AkhmadBabaev** [comment]
![изображение](https://user-images.githubusercontent.com/51095975/111276408-5ebacd80-8648-11eb-8979-2a4d42ce4883.png)

**Comment by AkhmadBabaev** [comment]
> Нет, все правильно. Это uikit, там позиционирование абсолютное между блоками элементов.

Да, моя ошибка, такое нормально. Ты вроде как первый у кого я такое заметил, чаще с помощью margin позиционируют относительно верхнего соседа )

**Comment by rsilivestr** [comment]
>Лучше явно добавить данный футер на страницу так как в макете он присутствует.

В iframe? Там же на media queries все завязано.

**Comment by AkhmadBabaev** [comment]
> В iframe? Там же на media queries все завязано.

Я про страницу headers & footers.

**Comment by rsilivestr** [comment]
>Я про страницу headers & footers.

И я про нее же. Футер изменяется при изменении ширины viewport. Кроме как iframe у меня идей нет.

**Comment by rsilivestr** [comment]
>В макете рамка имеет градиент, а сердце нет, у тебя наоборот )

В toggle и radio наоборот. Думаю, это неточность макета.

![image](https://user-images.githubusercontent.com/31914503/111278738-f5888980-864a-11eb-93bf-2a0566fb832f.png)

**Comment by AkhmadBabaev** [comment]
> И я про нее же. Футер изменяется при изменении ширины viewport. Кроме как iframe у меня идей нет.

На текущий момент с ребят требуют его явного добавления (хотя этот момент ещё стоит обсудить), ты можешь модификатор создать под такое поведение.

**Comment by rsilivestr** [comment]
>На текущий момент с ребят требуют его явного добавления (хотя этот момент ещё стоит обсудить), ты можешь модификатор создать под такое поведение.

Модификатор, который нужен только для uikit? Ну не знаю.

**Comment by AkhmadBabaev** [comment]
> Модификатор, который нужен только для uikit? Ну не знаю.

Говорю как вариант, на практике так лучше не делать. Можешь попробовать ui footer создать, либо iframe, выбор за тобой.

**Comment by rsilivestr** [comment]
> ![изображение](https://user-images.githubusercontent.com/51095975/111221608-c4c53780-85eb-11eb-94bd-e90a6df8c04a.png)
> 
> Что-то пошло не так.

Это второй сверху dropdown? Я его сделал чисто декоративным (как и два справа от него) - чтобы был постоянно открыт, как в uikit.

**Comment by AkhmadBabaev** [comment]
> Я его сделал чисто декоративным (как и два справа от него) - чтобы был постоянно открыт, как в uikit.

На это я обратил внимание, на скрине я указывал на то, что какие-то значения уже по дефолту выбраны, но при этом в тайтле ничего нет, тоже самое касается и соседей с права.

**Comment by AkhmadBabaev** [comment]
footer всегда должен находиться в нижней части страницы, даже если контента помимо хеадера и футера у страницы нет. Страница search-room не проходит эту проверку ) Остальные не проверял

**Comment by AkhmadBabaev** [comment]
Все страницы кроме ui должны тянуться от 320px до 1920px.
