### ISSUE TITLE
UI-Kit

### ISSUE THREAD

**Issue by Fr0stmourne** [rsilivestr/FSD2ndTask#5]
- Тут стрелочка все же не просто декоративный элемент, а кнопка отправки, иначе форму просто не отправить никак) 

![image](https://user-images.githubusercontent.com/46089168/98077887-144b6800-1e82-11eb-8210-d3be2dab9e9c.png)

- В этой области что-то странное творится, вот этот изначально открытый дропдаун я закрыть не могу (остальные 2 справа тоже кстати), но под ним что-то двигается
![image](https://user-images.githubusercontent.com/46089168/98078010-4a88e780-1e82-11eb-9a06-4f24f021d569.png)

**Comment by Fr0stmourne** [comment]
- На всей карточке висит cursor: pointer, хотя это не ссылка и провзаимодействовать с ней нельзя никак
![image](https://user-images.githubusercontent.com/46089168/98078371-00543600-1e83-11eb-9321-08873f064ac7.png)

- В той же карточке что-то со шрифтами, 888 явно не так выглядит

- Было бы здорово сделать работающий слайдер с картинками

**Comment by Fr0stmourne** [comment]
- При клике по кнопке применить в дропдауне лучше его сразу закрывать

- С футерами подразумевается, что нижний - мобильная версия верхнего
![image](https://user-images.githubusercontent.com/46089168/98078765-b750b180-1e83-11eb-9b77-8530ce4dddb0.png)

**Comment by rsilivestr** [comment]
>Тут стрелочка все же не просто декоративный элемент, а кнопка отправки, иначе форму просто не отправить никак)

Добавил блок для этой формы в 24a1105

>В этой области что-то странное творится, вот этот изначально открытый дропдаун я закрыть не могу (остальные 2 справа тоже кстати), но под ним что-то двигается

Движение убрал в d725d8b
Эти дропдауны не закрываются специально для uikit (иначе может быть один только один)

>На всей карточке висит cursor: pointer, хотя это не ссылка и провзаимодействовать с ней нельзя никак

Убрал в a3a8836

>В той же карточке что-то со шрифтами, 888 явно не так выглядит

С google-fonts скачал правильный quicksand a494965

>При клике по кнопке применить в дропдауне лучше его сразу закрывать

Сделал в 5ef163b

**Comment by rsilivestr** [comment]
>Было бы здорово сделать работающий слайдер с картинками

788f02f

**Comment by rsilivestr** [comment]
>С футерами подразумевается, что нижний - мобильная версия верхнего

fdffab1

**Comment by Fr0stmourne** [comment]
- У меня теперь пустая кнопка без стрелки
![image](https://user-images.githubusercontent.com/46089168/99268599-6c954900-2836-11eb-83c9-2d95b6ee4de6.png)

- По карточке комнаты:
    - Нужно где-то ссылку сделать, иначе просто не попасть на страницу этого номера.  
    - Нужно добавить кнопки с тенями с макета, которые показываются при наведении
![image](https://user-images.githubusercontent.com/46089168/99271382-ee39a680-2837-11eb-9f95-04607a0c2b66.png)
    - Еще там отвалилась рамка между первой и второй строчками

**Comment by Fr0stmourne** [comment]
- Валидация отвалилась
![image](https://user-images.githubusercontent.com/46089168/99272664-1aa1f280-2839-11eb-9f52-8743cc541080.png)

**Comment by rsilivestr** [comment]
>пустая кнопка без стрелки
>Нужно где-то ссылку сделать
>добавить кнопки с тенями
>отвалилась рамка между первой и второй строчками
>Валидация отвалилась

Исправил в f40092f

**Comment by Fr0stmourne** [comment]
Теперь стрелка есть, но текст наезжает
![image](https://user-images.githubusercontent.com/46089168/99970044-59d9c180-2dac-11eb-8703-2620a00e711f.png)

**Comment by rsilivestr** [comment]
>Теперь стрелка есть, но текст наезжает

Исправил в 66df3a10410b7d8dbcae9259ec00af390f1ab558

**Comment by Fr0stmourne** [comment]
- жирный шрифт для чисел сломался
![image](https://user-images.githubusercontent.com/46089168/101035348-c6627680-358b-11eb-904e-c8084a544aac.png)

**Comment by rsilivestr** [comment]
https://github.com/rsilivestr/FSD2ndTask/issues/5#issuecomment-738028666 исправил в 9cf0b69

**Comment by Fr0stmourne** [comment]
Вроде снизу около копирайта не должно быть логотипа
![image](https://user-images.githubusercontent.com/46089168/101526041-319db580-399d-11eb-826b-66c12664d6a1.png)

**Comment by Fr0stmourne** [comment]
Думаю, на эти элементы стоит cursor: pointer повесить, это всё же не обычные инпуты
![image](https://user-images.githubusercontent.com/46089168/101526761-20a17400-399e-11eb-8332-5e1250646ec3.png)

**Comment by Fr0stmourne** [comment]
Тут что-то странное с кнопками творится
![image](https://user-images.githubusercontent.com/46089168/101527429-0c11ab80-399f-11eb-917f-d463d3b4c97e.png)

**Comment by Fr0stmourne** [comment]
На странице с деталями номера все влево уехало
![image](https://user-images.githubusercontent.com/46089168/101527737-71fe3300-399f-11eb-96a2-de298db91347.png)

**Comment by rsilivestr** [comment]
>На странице с деталями номера все влево уехало

Исправил.

>cursor: pointer для dropdown

Добавил.

>снизу около копирайта не должно быть логотипа

Исправил media queries.

>Тут что-то странное с кнопками творится

Как возпроизвести? У меня все ок с кнопками... тестировал в firefox и chromium.
![image](https://user-images.githubusercontent.com/31914503/101673264-fd42fb80-3a67-11eb-9a2c-485442651929.png)

**Comment by Fr0stmourne** [comment]
С кнопками и у меня уже нормально всё, не знаю, что в прошлый раз случилось
